// Grace Lee
// CPSC 120-01
// 2020-12-14
// grace1@csu.fullerton.edu
// @gracelee2
//
// Lab 13-02
//
// Calculates the BMR of a person using the Mifflin St Jeor equation.
//

#include <algorithm>
#include <cstdlib>
#include <iostream>
#include <iterator>
#include <random>
#include <vector>

#include "rng.h"
#include "utility.h"

using namespace std;

/// Entry point to the calc_average_plusplus program
/// \remark Must have at least 3 arguments. The first argument is the minimum
/// number generated by the random number generator, the second argument
/// is the maximum number generated by the random number generator, and
/// the third argument is how many elements to insert into the vector.
int main(int argc, char* argv[]) {
  auto args = vector<string>(argv, argv + argc);
  if (args.size() < 4) {
    ErrorMessage(
        "Please provide two positive integers as the maximum and "
        "minimum for this exercise and the number of integers to "
        "generate.");
    exit(1);
  }

  string minimum;
  string maximum;
  string nelements;
  try {
    minimum = args.at(1);
    maximum = args.at(2);
    nelements = args.at(3);
  } catch (exception const& problem) {
    cout << "There was a problem getting the file name.\n";
    cout << problem.what() << "\n";
    exit(1);
  }

  int minimum_number = 0;
  int maximum_number = 0;
  int number_elements = 0;
  try {
    minimum_number = stoi(minimum);
  } catch (exception const& problem) {
    cout << problem.what() << "\n";
    ErrorMessage("Trouble converting the first argument to a number.");
    exit(1);
  }

  try {
    maximum_number = stoi(maximum);
  } catch (exception const& problem) {
    cout << problem.what() << "\n";
    ErrorMessage("Trouble converting the second argument to a number.");
    exit(1);
  }

  try {
    number_elements = stoi(nelements);
  } catch (exception const& problem) {
    cout << problem.what() << "\n";
    ErrorMessage("Trouble converting the third argument to a number.");
    exit(1);
  }

  if (maximum_number <= minimum_number || maximum_number < 0 ||
      minimum_number < 0) {
    ErrorMessage(
        "Please make sure your first number is less than your second "
        "number and that they are both positive integers.");
    exit(1);
  }

  RandomNumberGenerator rng(minimum_number, maximum_number);
  vector<int> random_numbers(number_elements);

  FillVector(random_numbers, number_elements, rng);
  PrintVector(random_numbers);
  float average = CalculateAverage(random_numbers);
  cout << "The average value of the vector is " << average << "\n";
  int median = CalculateMedian(random_numbers);
  cout << "The median value of the vector is " << median << "\n";
  int mode = CalculateMode(random_numbers);
  cout << "The mode of the vector is " << mode << "\n";

  return 0;
}
